function(check_san_option value)  
string(LENGTH "${SAN}" san_length)  
  if (san_length EQUAL 0)
    set("SAN_OPTION" 0 PARENT_SCOPE)
    return()
  endif()
  string(REPLACE ":" ";" flag_list ${SAN})  
  list(FIND flag_list "${value}" flag_index)
  if(NOT flag_index EQUAL -1)
    set("SAN_OPTION" 1 PARENT_SCOPE)
    return()
  endif()
  set("SAN_OPTION" 0 PARENT_SCOPE)
endfunction()