include(${CMAKE_CURRENT_LIST_DIR}/check_san_option.cmake)

check_san_option("ASAN")
set(ASAN ${SAN_OPTION})
check_san_option("LSAN")
set(LSAN ${SAN_OPTION})
check_san_option("MSAN")
set(MSAN ${SAN_OPTION})
check_san_option("TSAN")
set(TSAN ${SAN_OPTION})
check_san_option("UBSAN")
set(UBSAN ${SAN_OPTION})

if(ASAN)
  print("Address Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/asan.cmake)
elseif(LSAN)
  print("Leak Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/lsan.cmake)
elseif(MSAN)
  print("Memory Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/msan.cmake)
elseif(TSAN)
  print("Thread Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/tsan.cmake)
elseif(UBSAN)
  print("Undefined Behavior Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/ubsan.cmake)
endif()
