name: Build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
    - github-action

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        compiler: [{
          "cc": "gcc",
          "cxx": "g++"
         }, {
          "cc": "clang",
          "cxx": "clang++"
        }]
    steps:
    - uses: actions/checkout@v1
      name: checkout
      with:
        clean: true
        fetch-depth: 1
    - name: install dependencies
      run: |
        set -e
        sudo apt-get update || true
        sudo apt-get install -y apt-utils build-essential libssl-dev cmake python3 python3-pip
        sudo pip install conan
    - name: Cache Conan Data
      uses: actions/cache@v3
      env:
        cache-name: conan-data
      with:
        # caching node_modules
        path: ~/.conan/data
        key: ${{ matrix.compiler.cc }}-${{ env.cache-name }}
        restore-keys: |
          ${{ matrix.compiler.cc }}-${{ env.cache-name }}
    - name: select gcc
      if: matrix.compiler.cc == 'gcc'
      run: |
        sudo apt install gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        sudo update-alternatives --set gcc /usr/bin/gcc-11
    - name: select clang
      if: matrix.compiler.cc == 'clang'
      run: |
        sudo apt-get install -y clang
    - name: cmake
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
        SORALOG_SSH_KEY: ${{ secrets.SORALOGDEP }}
        SQLITE_SSH_KEY: ${{ secrets.SQLITEDEP }}
      run: |
        set -e
        conan profile new default
        conan profile update settings.arch=x86_64 default
        conan profile update settings.os=Linux default
        if [ "$CC" = "gcc" ]; then
          conan profile update settings.compiler=gcc default
          conan profile update settings.compiler.libcxx=libstdc++11 default
        fi

        # eval `ssh-agent -s`
        # ssh-add - <<< '${{ secrets.LIBP2PDEP }}'
        # ssh-add - <<< '${{ secrets.SORALOGDEP }}'

        mkdir -p ~/.ssh/
        echo "${SORALOG_SSH_KEY}" > ~/.ssh/soralog.key
        chmod 400 ~/.ssh/soralog.key
        echo "${SQLITE_SSH_KEY}" > ~/.ssh/sqlite.key
        chmod 400 ~/.ssh/sqlite.key
        echo Host soralog                       > ~/.ssh/config
        echo   HostName github.com              >> ~/.ssh/config
        echo   IdentityFile ~/.ssh/soralog.key  >> ~/.ssh/config
        echo   User git                         >> ~/.ssh/config
        echo                                    >> ~/.ssh/config
        echo Host sqlite                        >> ~/.ssh/config
        echo   HostName github.com              >> ~/.ssh/config
        echo   IdentityFile ~/.ssh/sqlite.key   >> ~/.ssh/config
        echo   User git                         >> ~/.ssh/config
        eval `ssh-agent -s`

        mkdir build
        cd build
        # cmake ..
        cmake -DSORALOG_GITHUB_HOST=soralog -DSQLITE_GITHUB_HOST=sqlite ..
        make
