name: Build

on: [push] # for testing; TODO restrict to master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        compiler: [{
          "cc": "gcc",
          "cxx": "g++"
         }, {
          "cc": "clang",
          "cxx": "clang++"
        }]
    steps:
    - uses: actions/checkout@v1
      name: checkout
      with:
        clean: true
        fetch-depth: 1
    - name: install dependencies
      run: |
        set -e
        sudo apt-get update || true
        sudo apt-get install -y apt-utils build-essential libssl-dev cmake python3 python3-pip
        sudo pip install conan
    - name: cmake
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        set -e
        conan profile new default
        if [ "$CC" = "gcc" ]; then
          conan profile update settings.compiler=gcc default
          conan profile update settings.compiler.libcxx=libstdc++11 default
        fi
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.LIBP2PDEP }}'
        mkdir build
        cd build
        cmake ..
        make
